name: Run Command Workflow

on: 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Checkout Source Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Dependencies
      run: |
        sudo apt-get -yqq install curl
        pip install agbenchmark

    - name: Replace Placeholder
      run: |
        cp config_template.yaml config.yaml
        sed -i 's|YOUR_OPEN_API_KEY|${{ secrets.OPENAI_API_KEY }}|g' config.yaml
        sed -i 's|workspace/input/{agent_id}|workspace/input|g' config.yaml
        sed -i 's|workspace/output/{agent_id}/{agent_execution_id}|workspace/output|g' config.yaml
        sed -i 's|YOUR_SERPER_API_KEY|${{ secrets.SERPER_API_KEY }}|g' config.yaml

    - name: Docker Compose Build and Run
      run: docker-compose up -d --build

    - name: Wait for Docker service to start
      run: |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000/api/configs/get/env)" != "200" ]]; do sleep 5; done

    - name: Run agbenchmark
      run: agbenchmark start
