name: Run Command Workflow

on: 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Checkout Source Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get -yqq install curl
        pip install agbenchmark

    - name: Check directory
      run: |
        pwd
        ls

    - name: Replace Placeholder
      run: |
        cp config_template.yaml config.yaml
        sed -i 's|YOUR_OPEN_API_KEY|'"${{ secrets.OPENAI_API_KEY }}"'|g' config.yaml
        sed -i 's|workspace/input/{agent_id}|workspace/input|g' config.yaml
        sed -i 's|workspace/output/{agent_id}/{agent_execution_id}|workspace/output|g' config.yaml
        sed -i 's|YOUR_SERPER_API_KEY|'"${{ secrets.SERPER_API_KEY }}"'|g' config.yaml
        sed -i 's/OPENAI_API_KEY:.*/OPENAI_API_KEY: "'"${{ secrets.OPENAI_API_KEY }}"'"/' config.yaml
