name: Test ENV

on: 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Checkout Source Code
      uses: actions/checkout@v2

    - name: Check directory
      run: |
        pwd
        ls
               
    - name: print secrets     
      env:
        SUPER_SECRET: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "hello"
        echo $SUPER_SECRET
        echo "world"
